drop table if exists t_bodyposture;

/*==============================================================*/
/* Table: t_bodyposture                                         */
/*==============================================================*/
create table t_bodyposture
(
   id                     bigint auto_increment,
   time                   VARCHAR(255),
   dist_l                 FLOAT(8),
   dist_R                 FLOAT(8),
   roll_l                 FLOAT(8),
   pitch_l                Float(8),
   yaw_l                  Float(8),
   roll_r                 Float(8),
   pitch_r                Float(8),
   yaw_r                  Float(8),
   hips_R                 Float(8),
   hips_P                 Float(8),
   hips_Y                 Float(8),
   rightUpLeg_R           Float(8),
   rightUpLeg_P           Float(8),
   rightUpLeg_Y           Float(8),
   rightLeg_R             Float(8),
   rightLeg_P             Float(8),
   rightLeg_Y             Float(8),
   rightFoot_R            Float(8),
   rightFoot_P            Float(8),
   rightFoot_Y            Float(8),
   leftUpLeg_R            Float(8),
   leftUpLeg_P            Float(8),
   leftUpLeg_Y            Float(8),
   leftLeg_R              Float(8),
   leftLeg_P              Float(8),
   leftLeg_Y              Float(8),
   leftFoot_R             Float(8),
   leftFoot_P             Float(8),
   leftFoot_Y             Float(8),
   spine_R                Float(8),
   spine_P                Float(8),
   spine_Y                Float(8),
   head_R                 Float(8),
   head_P                 Float(8),
   head_Y                 Float(8),
   rightShoulder_R        Float(8),
   rightShoulder_P        Float(8),
   rightShoulder_Y        Float(8),
   rightArm_R             Float(8),
   rightArm_P             Float(8),
   rightArm_Y             Float(8),
   rightForeArm_R         Float(8),
   rightForeArm_P         Float(8),
   rightForeArm_Y         Float(8),
   rightHand_R            Float(8),
   rightHand_P            Float(8),
   rightHand_Y            Float(8),
   leftShoulder_R         Float(8),
   leftShoulder_P         Float(8),
   leftShoulder_Y         Float(8),
   leftArm_R              Float(8),
   leftArm_P              Float(8),
   leftArm_Y              Float(8),
   leftForeArm_R          Float(8),
   leftForeArm_P          Float(8),
   leftForeArm_Y          Float(8),
   leftHand_R             Float(8),
   leftHand_P             Float(8),
   leftHand_Y             Float(8),
   primary key (id)
);
